// https://docs.expo.dev/guides/using-eslint/
//
// Flat config: eslint-config-expo v10 (SDK 54) requires ESLint 9, which dropped
// `.eslintrc.js`. The generated native projects are ignored — they are build output,
// regenerated by `expo prebuild`, and linting them reports on code nobody wrote.
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
    expoConfig,
    {
        ignores: ['dist/*', 'android/*', 'ios/*', 'node_modules/*', '.expo/*'],
    },
    {
        rules: {
            /**
             * Off on purpose, and it is not a suppression.
             *
             * `react/no-unescaped-entities` exists because react-dom renders into HTML,
             * where a bare `>` or `"` in text can be read as markup. React Native has no
             * HTML parser — `<Text>don't</Text>` renders exactly that — so the rule flags
             * 36 correct apostrophes and protects against nothing. It arrived with
             * eslint-config-expo v10 in the SDK 54 upgrade; escaping every apostrophe to
             * `&apos;` would make the copy harder to read to satisfy a web-only concern.
             */
            'react/no-unescaped-entities': 'off',
        },
    },
]);
